
#ifndef NUMERICS_H
# define NUMERICS_H

# define RPL_WELCOME			1
# define RPL_YOURHOST			2
# define RPL_CREATED			3
# define RPL_MYINFO				4
# define RPL_UMODEIS			221 
# define RPL_LUSERCLIENT		251 
# define RPL_LUSEROP			252
# define RPL_LUSERCHANNELS		254
# define RPL_LUSERME			255
# define RPL_AWAY				301
# define RPL_UNAWAY				305
# define RPL_NOWAWAY			306
# define RPL_ENDOFWHO			315
# define RPL_LISTSTART			321
# define RPL_LIST				322  
# define RPL_LISTEND			323
# define RPL_CHANNELMODEIS		324  
# define RPL_CREATIONTIME		329  
# define RPL_NOTOPIC			331 
# define RPL_TOPIC				332 
# define RPL_TOPICWHOTIME		333 
# define RPL_INVITING			341 
# define RPL_INVITELIST			346  
# define RPL_ENDOFINVITELIST	347 
# define RPL_EXCEPTLIST			348  
# define RPL_ENDOFEXCEPTLIST	349 
# define RPL_WHOREPLY			352 
# define RPL_NAMREPLY			353  
# define RPL_ENDOFNAMES			366  
# define RPL_BANLIST			367 
# define RPL_ENDOFBANLIST		368
# define RPL_MOTD				372 
# define RPL_MOTDSTART			375 
# define RPL_ENDOFMOTD			376 
# define ERR_NOSUCHNICK			401 
# define ERR_NOSUCHSERVER		402 
# define ERR_NOSUCHCHANNEL		403 
# define ERR_CANNOTSENDTOCHAN	404 
# define ERR_NORECIPIENT		411 
# define ERR_NOTEXTTOSEND		412 
# define ERR_UNKNOWNCOMMAND		421 
# define ERR_NOMOTD				422 
# define ERR_NONICKNAMEGIVEN	431 
# define ERR_NICKNAMEINUSE		433  
# define ERR_USERNOTINCHANNEL	441  
# define ERR_NOTONCHANNEL		442  
# define ERR_USERONCHANNEL		443  
# define ERR_NOTREGISTERED		451 
# define ERR_NEEDMOREPARAMS		461 
# define ERR_ALREADYREGISTERED	462 
# define ERR_PASSWDMISMATCH		464 
# define ERR_CHANNELISFULL		471 
# define ERR_UNKNOWNMODE		472 
# define ERR_INVITEONLYCHAN		473 
# define ERR_BANNEDFROMCHAN		474 
# define ERR_BADCHANNELKEY		475 
# define ERR_CHANOPRIVSNEEDED	482
# define ERR_UMODEUNKNOWNFLAG	501 
# define ERR_USERSDONTMATCH		502 
# define ERR_INVALIDMODEPARAM	696 

# define CRLF					"\r\n"

#endif